# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ff69bbf2b6cb22ddf5890dfa598bdc63021fb074f1fa5987e92482e608e4437cc345d07b929ffba3deda54c97b817ec156d0502c8e0bec2b5a3d0733294d76b

test:
  secret_key_base: de179b1ca9d38429263a0069481c2e8d2d19bcb9dee7f4ac97f53db3c67034b59b59964cbc0b0cd35760d7ee38eba8bd79ff20e4d11f9ba2d8dee7b44002caae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
